apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: team-operator
  template:
    metadata:
      labels:
        name: team-operator
    spec:
      serviceAccountName: team-operator
      containers:
        - name: team-operator
          image: centosadmin/team-operator:v0.0.2
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "team-operator"
